/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface CodeExampleProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Example source code
   */
  children: string | number | boolean | Function;
  /**
   * Description text - default is "Example"
   */
  desc?: string;
  /**
   * `children` as literal source code string for documentation
   * 
   * Autogenerate this using [webframe-docs](https://www.npmjs.com/package/webframe-docs) CLI.
   */
  source?: string;
}
/**
 * Renders `children` along with its source code representation.
 * @see https://webframe.app/docs/ui/views/CodeExample
 */
export function CodeExample(props: CodeExampleProps): JSX.Element;

export default CodeExampleMemo;
export const CODE_TRIM_REGEX: RegExp;
export const CODE_INDENT_REGEX: RegExp;
declare const CodeExampleMemo: React.NamedExoticComponent<CodeExampleProps>;
import * as React from 'react';
