/// Generated by Webframe.app | Do not edit this file directly! \\\
/**
 * Component Props Table View.
 * @see https://webframe.app/docs/ui/views/PropsTable
 * @example:
 *  <PropsTable component={Button} />
 *  ┌────────────────┬───────────────────────┬──────────────┬──────────────────┐
 *  │ Prop           │ Type                  │ Default      │ Description      │
 *  ├────────────────┼───────────────────────┼──────────────┼──────────────────┤
 *  │ children       │ String | Number       │ Required     │ Button content   │
 *  ├────────────────┼───────────────────────┼──────────────┼──────────────────┤
 *  │ type           │ 'button' | 'submit'   │ 'button'     │                  │
 *  └────────────────┴───────────────────────┴──────────────┴──────────────────┘
 */
export function PropsTable({ component, manifest, ...view }: {
    [x: string]: any;
    component: any;
    manifest?: {
        Tooltip: {
            propTypes: {
                children: {
                    c: string;
                };
                on: {
                    c: string;
                };
                position: {
                    c: string;
                };
                align: {
                    c: string;
                };
                animation: {
                    c: string;
                };
                delay: {
                    c: string;
                };
                embedded: {
                    c: string;
                };
                offset: {
                    c: string;
                };
                openInitially: {
                    c: string;
                };
                onOpen: {
                    c: string;
                };
                onClose: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                theme: {
                    c: string;
                };
                tooltipClass: {
                    c: string;
                };
            };
            defaultProps: {
                animation: {
                    v: string;
                };
                delay: {
                    v: string;
                };
                on: {
                    v: string;
                };
                offset: {
                    v: string;
                };
                position: {
                    v: string;
                };
                theme: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        Accordion: {
            propTypes: {
                children: {
                    c: string;
                };
                duration: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                open: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
            };
        };
        Badge: {
            propTypes: {
                count: {
                    c: string;
                };
                maxDigits: {
                    c: string;
                };
            };
            defaultProps: {
                maxDigits: {
                    v: string;
                };
            };
        };
        Breadcrumb: {
            propTypes: {
                items: {
                    c: string;
                };
                children: {
                    c: string;
                };
            };
        };
        Button: {
            propTypes: {
                children: {
                    c: string;
                };
                className: {};
                style: {};
                active: {
                    c: string;
                };
                disabled: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                type: {
                    c: string;
                };
                tooltip: {};
                _ref: {};
            };
        };
        Buttons: {
            propTypes: {
                items: {
                    c: string;
                };
                vertical: {
                    c: string;
                };
                children: {
                    c: string;
                };
            };
        };
        Divider: {
            propTypes: {
                className: {};
                style: {};
            };
        };
        DropdownMenu: {
            defaultProps: {
                iconClose: {
                    v: string;
                };
                iconOpen: {
                    v: string;
                };
            };
            propTypes: {
                children: {
                    c: string;
                };
                open: {
                    c: string;
                };
                btnProps: {
                    c: string;
                };
                iconProps: {
                    c: string;
                };
                iconOpen: {};
                iconClose: {};
                menu: {
                    c: string;
                };
                tooltipProps: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        ErrorContent: {
            propTypes: {
                items: {};
            };
        };
        ErrorTable: {
            propTypes: {
                items: {};
            };
        };
        Expand: {
            propTypes: {
                children: {
                    c: string;
                };
                direction: {
                    c: string;
                };
                duration: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                id: {
                    c: string;
                };
                index: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                open: {
                    c: string;
                };
                asPanel: {
                    c: string;
                };
            };
            defaultProps: {
                direction: {
                    v: string;
                };
                duration: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        ExpandTab: {
            propTypes: {
                children: {
                    c: string;
                };
                onClick: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        ExpandPanel: {
            propTypes: {
                children: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        Highlighter: {
            defaultProps: {};
            propTypes: {
                children: {
                    c: string;
                };
                language: {
                    c: string;
                };
                PreTag: {
                    c: string;
                };
            };
        };
        Icon: {
            propTypes: {
                name: {
                    c: string;
                };
                font: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        Image: {
            defaultProps: {
                name: {
                    v: string;
                    c: string;
                };
                loading: {
                    v: string;
                };
                decoding: {
                    v: string;
                };
            };
            propTypes: {
                name: {
                    c: string;
                };
                dir: {
                    c: string;
                };
                src: {
                    c: string;
                };
                alt: {
                    c: string;
                };
                loading: {};
                decoding: {};
                className: {};
                style: {};
            };
        };
        ImageSwatch: {
            defaultProps: {
                name: {
                    v: string;
                };
            };
            propTypes: {
                src: {
                    c: string;
                };
                small: {};
                large: {};
                className: {};
                style: {};
            };
        };
        JsonView: {
            propTypes: {
                data: {
                    c: string;
                };
                dark: {
                    c: string;
                };
                open: {
                    c: string;
                };
                theme: {
                    c: string;
                };
            };
            defaultProps: {
                theme: {
                    v: string;
                };
            };
        };
        Loader: {
            defaultProps: {
                loading: {
                    v: string;
                };
            };
            propTypes: {
                loading: {
                    c: string;
                };
                children: {
                    c: string;
                };
                size: {
                    c: string;
                };
                iconClass: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        Markdown: {
            propTypes: {
                children: {};
                components: {
                    c: string;
                };
                remarkPlugins: {};
                rehypePlugins: {};
                remarkRehypeOptions: {};
            };
        };
        Modal: {
            defaultProps: {
                canClose: {
                    v: string;
                };
            };
            propTypes: {
                canClose: {
                    c: string;
                };
                open: {
                    c: string;
                };
                onClose: {
                    c: string;
                };
            };
        };
        ShadowDOM: {
            propTypes: {
                mode: {};
                delegatesFocus: {};
                styleSheets: {
                    c: string;
                };
                ssr: {};
                children: {};
            };
            defaultProps: {
                mode: {
                    v: string;
                };
                delegatesFocus: {
                    v: string;
                };
                styleSheets: {
                    v: string;
                };
            };
        };
        Spacer: {
            propTypes: {
                size: {};
                className: {};
                style: {};
            };
        };
        Spinner: {
            propTypes: {
                size: {};
                color: {};
                className: {};
            };
        };
        Tabs: {
            propTypes: {
                activeId: {
                    c: string;
                };
                defaultId: {
                    c: string;
                };
                children: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                rtl: {
                    c: string;
                };
                vertical: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                items: {
                    c: string;
                };
                tabListProps: {
                    c: string;
                };
            };
        };
        TabList: {
            propTypes: {
                className: {};
                role: {};
            };
            defaultProps: {
                className: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        Tab: {
            propTypes: {
                id: {
                    c: string;
                };
                onClick: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                    c: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        TabPanel: {
            propTypes: {
                id: {
                    c: string;
                };
                children: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                scroll: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        Text: {
            propTypes: {
                children: {
                    c: string;
                };
                className: {};
                style: {};
                tooltip: {};
                _ref: {};
            };
        };
        View: {
            defaultProps: {
                defaultProp: {
                    v: string;
                };
            };
            propTypes: {
                className: {
                    c: string;
                };
                style: {
                    c: string;
                };
                col: {
                    c: string;
                };
                row: {
                    c: string;
                };
                grid: {
                    c: string;
                };
                fill: {
                    c: string;
                };
                reverse: {
                    c: string;
                };
                rtl: {
                    c: string;
                };
                left: {
                    c: string;
                };
                right: {
                    c: string;
                };
                top: {
                    c: string;
                };
                bottom: {
                    c: string;
                };
                center: {
                    c: string;
                };
                middle: {
                    c: string;
                };
                sound: {
                    c: string;
                };
                children: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                preventOffset: {
                    c: string;
                };
                tooltip: {};
                scroll: {
                    c: string;
                };
                scrollAlongDirectionOnly: {
                    c: string;
                };
                scrollClass: {
                    c: string;
                };
                scrollStyle: {
                    c: string;
                };
                scrollProps: {
                    c: string;
                };
                scrollOffset: {
                    c: string;
                };
                scrollOverflowProps: {
                    c: string;
                };
                scrollReversed: {
                    c: string;
                };
                scrollRef: {
                    c: string;
                };
                _ref: {
                    c: string;
                };
            };
        };
        VirtualList: {
            defaultProps: {
                fill: {
                    v: string;
                };
                scroll: {
                    v: string;
                };
                initialItems: {
                    v: string;
                };
                renderRadius: {
                    v: string;
                };
            };
            propTypes: {
                items: {
                    c: string;
                };
                initialItems: {
                    c: string;
                };
                grid: {
                    c: string;
                };
                row: {
                    c: string;
                };
                renderItem: {
                    c: string;
                };
                renderRadius: {
                    c: string;
                };
            };
        };
        VirtualListItem: {
            propTypes: {
                children: {};
            };
        };
        Checkbox: {
            defaultProps: {
                className: {
                    v: string;
                };
                checkedValue: {
                    v: string;
                };
                uncheckedValue: {
                    v: string;
                };
            };
            propTypes: {
                label: {
                    c: string;
                };
                id: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                value: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                checkedValue: {
                    c: string;
                };
                uncheckedValue: {
                    c: string;
                };
                readonly: {
                    c: string;
                };
            };
        };
        Input: {
            defaultProps: {
                type: {
                    v: string;
                };
                helpTransition: {
                    v: string;
                };
            };
            propTypes: {
                type: {
                    c: string;
                };
                id: {
                    c: string;
                };
                info: {
                    c: string;
                };
                error: {
                    c: string;
                };
                helpTransition: {
                    c: string;
                };
                compact: {
                    c: string;
                };
                controls: {
                    c: string;
                };
                controlProps: {
                    c: string;
                };
                tooltip: {};
            };
        };
        InputNative: {
            defaultProps: {
                type: {
                    v: string;
                };
            };
            propTypes: {
                compact: {
                    c: string;
                };
                controlledValue: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                value: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                label: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                normalize: {
                    c: string;
                };
                prefix: {
                    c: string;
                };
                suffix: {
                    c: string;
                };
                stickyPlaceholder: {
                    c: string;
                };
                noSpellCheck: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
            };
        };
        InputView: {
            defaultProps: {
                viewType: {
                    v: string;
                };
                controls: {
                    v: string;
                    c: string;
                };
                Input: {
                    v: string;
                };
                inputClicks: {
                    v: string;
                };
                inputOnlyAttrs: {
                    v: string;
                };
            };
            propTypes: {
                viewType: {
                    c: string;
                };
                Input: {
                    c: string;
                };
                inputClicks: {
                    c: string;
                };
                inputOnlyAttrs: {
                    c: string;
                };
                inputProps: {
                    c: string;
                };
                viewProps: {
                    c: string;
                };
            };
        };
        Select: {
            defaultProps: {
                focusIndex: {
                    v: string;
                };
                query: {
                    v: string;
                    c: string;
                };
                virtualOptionsMinimum: {
                    v: string;
                };
            };
            propTypes: {
                options: {
                    c: string;
                };
                optionProps: {
                    c: string;
                };
                optionsProps: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                onSearch: {
                    c: string;
                };
                onSelect: {
                    c: string;
                };
                onClickValue: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                addOption: {
                    c: string;
                };
                compact: {
                    c: string;
                };
                controlledValue: {
                    c: string;
                };
                openInitially: {
                    c: string;
                };
                excludeSelected: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                normalize: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                fixed: {
                    c: string;
                };
                query: {
                    c: string;
                };
                queryParser: {
                    c: string;
                };
                search: {
                    c: string;
                };
                searchNonce: {
                    c: string;
                };
                searchOptions: {
                    c: string;
                };
                upward: {
                    c: string;
                };
                value: {
                    c: string;
                };
                renderSelected: {
                    c: string;
                };
                noOptionsMsg: {
                    c: string;
                };
                virtualOptionsMinimum: {
                    c: string;
                };
            };
        };
        SelectNested: {
            defaultProps: {
                optionProps: {
                    v: string;
                };
                nestedIcon: {
                    v: string;
                    c: string;
                };
                nestedProps: {
                    v: string;
                };
            };
            propTypes: {
                nestedIcon: {
                    c: string;
                };
                options: {
                    c: string;
                };
                formatKey: {
                    c: string;
                };
                filterValue: {
                    c: string;
                };
            };
        };
        SelectOption: {
            propTypes: {
                option: {};
                onClick: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                focused: {
                    c: string;
                };
                selected: {
                    c: string;
                };
                search: {
                    c: string;
                };
                query: {
                    c: string;
                };
            };
        };
        Switch: {
            defaultProps: {
                className: {
                    v: string;
                };
                checkedValue: {
                    v: string;
                };
                uncheckedValue: {
                    v: string;
                };
            };
            propTypes: {
                controlledValue: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                checkedValue: {
                    c: string;
                };
                uncheckedValue: {
                    c: string;
                };
                label: {
                    c: string;
                };
                checkedLabel: {
                    c: string;
                };
                uncheckedLabel: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                value: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                id: {
                    c: string;
                };
            };
        };
        TextArea: {
            propTypes: {
                compact: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                value: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                label: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                resize: {
                    c: string;
                };
                noSpellCheck: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
            };
        };
        Upload: {
            defaultProps: {
                type: {
                    v: string;
                };
                hyphen: {
                    v: string;
                };
                loading: {
                    v: string;
                };
                iconSelect: {
                    v: string;
                };
                iconRemove: {
                    v: string;
                };
                onError: {
                    v: string;
                };
            };
            propTypes: {
                accept: {
                    c: string;
                };
                children: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                hyphen: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                maxFiles: {
                    c: string;
                };
                maxSize: {
                    c: string;
                };
                minSize: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                iconSelect: {
                    c: string;
                };
                iconRemove: {
                    c: string;
                };
                square: {
                    c: string;
                };
                value: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onError: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
            };
        };
        UploadGrid: {
            defaultProps: {
                maxFiles: {
                    v: string;
                };
                gap: {
                    v: string;
                };
                previewAccept: {
                    v: string;
                };
            };
            propTypes: {
                initialValues: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onChangeLast: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                maxFiles: {
                    c: string;
                };
                maxColumns: {
                    c: string;
                };
                gap: {
                    c: string;
                };
                kind: {
                    c: string;
                };
                noPreview: {
                    c: string;
                };
                noPreviewClean: {
                    c: string;
                };
                preview: {
                    c: string;
                };
                previewAccept: {
                    c: string;
                };
                previewClass: {
                    c: string;
                };
                square: {
                    c: string;
                };
                slotLabel: {
                    c: string;
                };
                types: {
                    c: string;
                };
            };
        };
        CodeExample: {
            propTypes: {
                children: {
                    c: string;
                };
                desc: {
                    c: string;
                };
                source: {
                    c: string;
                };
            };
        };
        PropsTable: {
            propTypes: {
                component: {
                    c: string;
                };
                manifest: {
                    c: string;
                };
            };
        };
        TypeHelpTooltip: {
            propTypes: {
                _type: {
                    c: string;
                };
                text: {
                    c: string;
                };
                desc: {
                    c: string;
                };
            };
        };
    } | undefined;
}): JSX.Element | null;

export default PropsTableMemo;
declare const PropsTableMemo: React.NamedExoticComponent<{
    [x: string]: any;
    component: any;
    manifest?: {
        Tooltip: {
            propTypes: {
                children: {
                    c: string;
                };
                on: {
                    c: string;
                };
                position: {
                    c: string;
                };
                align: {
                    c: string;
                };
                animation: {
                    c: string;
                };
                delay: {
                    c: string;
                };
                embedded: {
                    c: string;
                };
                offset: {
                    c: string;
                };
                openInitially: {
                    c: string;
                };
                onOpen: {
                    c: string;
                };
                onClose: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                theme: {
                    c: string;
                };
                tooltipClass: {
                    c: string;
                };
            };
            defaultProps: {
                animation: {
                    v: string;
                };
                delay: {
                    v: string;
                };
                on: {
                    v: string;
                };
                offset: {
                    v: string;
                };
                position: {
                    v: string;
                };
                theme: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        Accordion: {
            propTypes: {
                children: {
                    c: string;
                };
                duration: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                open: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
            };
        };
        Badge: {
            propTypes: {
                count: {
                    c: string;
                };
                maxDigits: {
                    c: string;
                };
            };
            defaultProps: {
                maxDigits: {
                    v: string;
                };
            };
        };
        Breadcrumb: {
            propTypes: {
                items: {
                    c: string;
                };
                children: {
                    c: string;
                };
            };
        };
        Button: {
            propTypes: {
                children: {
                    c: string;
                };
                className: {};
                style: {};
                active: {
                    c: string;
                };
                disabled: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                type: {
                    c: string;
                };
                tooltip: {};
                _ref: {};
            };
        };
        Buttons: {
            propTypes: {
                items: {
                    c: string;
                };
                vertical: {
                    c: string;
                };
                children: {
                    c: string;
                };
            };
        };
        Divider: {
            propTypes: {
                className: {};
                style: {};
            };
        };
        DropdownMenu: {
            defaultProps: {
                iconClose: {
                    v: string;
                };
                iconOpen: {
                    v: string;
                };
            };
            propTypes: {
                children: {
                    c: string;
                };
                open: {
                    c: string;
                };
                btnProps: {
                    c: string;
                };
                iconProps: {
                    c: string;
                };
                iconOpen: {};
                iconClose: {};
                menu: {
                    c: string;
                };
                tooltipProps: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        ErrorContent: {
            propTypes: {
                items: {};
            };
        };
        ErrorTable: {
            propTypes: {
                items: {};
            };
        };
        Expand: {
            propTypes: {
                children: {
                    c: string;
                };
                direction: {
                    c: string;
                };
                duration: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                id: {
                    c: string;
                };
                index: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                open: {
                    c: string;
                };
                asPanel: {
                    c: string;
                };
            };
            defaultProps: {
                direction: {
                    v: string;
                };
                duration: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        ExpandTab: {
            propTypes: {
                children: {
                    c: string;
                };
                onClick: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        ExpandPanel: {
            propTypes: {
                children: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        Highlighter: {
            defaultProps: {};
            propTypes: {
                children: {
                    c: string;
                };
                language: {
                    c: string;
                };
                PreTag: {
                    c: string;
                };
            };
        };
        Icon: {
            propTypes: {
                name: {
                    c: string;
                };
                font: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        Image: {
            defaultProps: {
                name: {
                    v: string;
                    c: string;
                };
                loading: {
                    v: string;
                };
                decoding: {
                    v: string;
                };
            };
            propTypes: {
                name: {
                    c: string;
                };
                dir: {
                    c: string;
                };
                src: {
                    c: string;
                };
                alt: {
                    c: string;
                };
                loading: {};
                decoding: {};
                className: {};
                style: {};
            };
        };
        ImageSwatch: {
            defaultProps: {
                name: {
                    v: string;
                };
            };
            propTypes: {
                src: {
                    c: string;
                };
                small: {};
                large: {};
                className: {};
                style: {};
            };
        };
        JsonView: {
            propTypes: {
                data: {
                    c: string;
                };
                dark: {
                    c: string;
                };
                open: {
                    c: string;
                };
                theme: {
                    c: string;
                };
            };
            defaultProps: {
                theme: {
                    v: string;
                };
            };
        };
        Loader: {
            defaultProps: {
                loading: {
                    v: string;
                };
            };
            propTypes: {
                loading: {
                    c: string;
                };
                children: {
                    c: string;
                };
                size: {
                    c: string;
                };
                iconClass: {
                    c: string;
                };
                className: {};
                style: {};
            };
        };
        Markdown: {
            propTypes: {
                children: {};
                components: {
                    c: string;
                };
                remarkPlugins: {};
                rehypePlugins: {};
                remarkRehypeOptions: {};
            };
        };
        Modal: {
            defaultProps: {
                canClose: {
                    v: string;
                };
            };
            propTypes: {
                canClose: {
                    c: string;
                };
                open: {
                    c: string;
                };
                onClose: {
                    c: string;
                };
            };
        };
        ShadowDOM: {
            propTypes: {
                mode: {};
                delegatesFocus: {};
                styleSheets: {
                    c: string;
                };
                ssr: {};
                children: {};
            };
            defaultProps: {
                mode: {
                    v: string;
                };
                delegatesFocus: {
                    v: string;
                };
                styleSheets: {
                    v: string;
                };
            };
        };
        Spacer: {
            propTypes: {
                size: {};
                className: {};
                style: {};
            };
        };
        Spinner: {
            propTypes: {
                size: {};
                color: {};
                className: {};
            };
        };
        Tabs: {
            propTypes: {
                activeId: {
                    c: string;
                };
                defaultId: {
                    c: string;
                };
                children: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                rtl: {
                    c: string;
                };
                vertical: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                items: {
                    c: string;
                };
                tabListProps: {
                    c: string;
                };
            };
        };
        TabList: {
            propTypes: {
                className: {};
                role: {};
            };
            defaultProps: {
                className: {
                    v: string;
                };
                role: {
                    v: string;
                };
            };
        };
        Tab: {
            propTypes: {
                id: {
                    c: string;
                };
                onClick: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                    c: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        TabPanel: {
            propTypes: {
                id: {
                    c: string;
                };
                children: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                scroll: {
                    c: string;
                };
            };
            defaultProps: {
                role: {
                    v: string;
                };
                _nodrag: {
                    v: string;
                };
            };
        };
        Text: {
            propTypes: {
                children: {
                    c: string;
                };
                className: {};
                style: {};
                tooltip: {};
                _ref: {};
            };
        };
        View: {
            defaultProps: {
                defaultProp: {
                    v: string;
                };
            };
            propTypes: {
                className: {
                    c: string;
                };
                style: {
                    c: string;
                };
                col: {
                    c: string;
                };
                row: {
                    c: string;
                };
                grid: {
                    c: string;
                };
                fill: {
                    c: string;
                };
                reverse: {
                    c: string;
                };
                rtl: {
                    c: string;
                };
                left: {
                    c: string;
                };
                right: {
                    c: string;
                };
                top: {
                    c: string;
                };
                bottom: {
                    c: string;
                };
                center: {
                    c: string;
                };
                middle: {
                    c: string;
                };
                sound: {
                    c: string;
                };
                children: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                preventOffset: {
                    c: string;
                };
                tooltip: {};
                scroll: {
                    c: string;
                };
                scrollAlongDirectionOnly: {
                    c: string;
                };
                scrollClass: {
                    c: string;
                };
                scrollStyle: {
                    c: string;
                };
                scrollProps: {
                    c: string;
                };
                scrollOffset: {
                    c: string;
                };
                scrollOverflowProps: {
                    c: string;
                };
                scrollReversed: {
                    c: string;
                };
                scrollRef: {
                    c: string;
                };
                _ref: {
                    c: string;
                };
            };
        };
        VirtualList: {
            defaultProps: {
                fill: {
                    v: string;
                };
                scroll: {
                    v: string;
                };
                initialItems: {
                    v: string;
                };
                renderRadius: {
                    v: string;
                };
            };
            propTypes: {
                items: {
                    c: string;
                };
                initialItems: {
                    c: string;
                };
                grid: {
                    c: string;
                };
                row: {
                    c: string;
                };
                renderItem: {
                    c: string;
                };
                renderRadius: {
                    c: string;
                };
            };
        };
        VirtualListItem: {
            propTypes: {
                children: {};
            };
        };
        Checkbox: {
            defaultProps: {
                className: {
                    v: string;
                };
                checkedValue: {
                    v: string;
                };
                uncheckedValue: {
                    v: string;
                };
            };
            propTypes: {
                label: {
                    c: string;
                };
                id: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                value: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                checkedValue: {
                    c: string;
                };
                uncheckedValue: {
                    c: string;
                };
                readonly: {
                    c: string;
                };
            };
        };
        Input: {
            defaultProps: {
                type: {
                    v: string;
                };
                helpTransition: {
                    v: string;
                };
            };
            propTypes: {
                type: {
                    c: string;
                };
                id: {
                    c: string;
                };
                info: {
                    c: string;
                };
                error: {
                    c: string;
                };
                helpTransition: {
                    c: string;
                };
                compact: {
                    c: string;
                };
                controls: {
                    c: string;
                };
                controlProps: {
                    c: string;
                };
                tooltip: {};
            };
        };
        InputNative: {
            defaultProps: {
                type: {
                    v: string;
                };
            };
            propTypes: {
                compact: {
                    c: string;
                };
                controlledValue: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                value: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                label: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                normalize: {
                    c: string;
                };
                prefix: {
                    c: string;
                };
                suffix: {
                    c: string;
                };
                stickyPlaceholder: {
                    c: string;
                };
                noSpellCheck: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
            };
        };
        InputView: {
            defaultProps: {
                viewType: {
                    v: string;
                };
                controls: {
                    v: string;
                    c: string;
                };
                Input: {
                    v: string;
                };
                inputClicks: {
                    v: string;
                };
                inputOnlyAttrs: {
                    v: string;
                };
            };
            propTypes: {
                viewType: {
                    c: string;
                };
                Input: {
                    c: string;
                };
                inputClicks: {
                    c: string;
                };
                inputOnlyAttrs: {
                    c: string;
                };
                inputProps: {
                    c: string;
                };
                viewProps: {
                    c: string;
                };
            };
        };
        Select: {
            defaultProps: {
                focusIndex: {
                    v: string;
                };
                query: {
                    v: string;
                    c: string;
                };
                virtualOptionsMinimum: {
                    v: string;
                };
            };
            propTypes: {
                options: {
                    c: string;
                };
                optionProps: {
                    c: string;
                };
                optionsProps: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                onSearch: {
                    c: string;
                };
                onSelect: {
                    c: string;
                };
                onClickValue: {
                    c: string;
                };
                onMount: {
                    c: string;
                };
                addOption: {
                    c: string;
                };
                compact: {
                    c: string;
                };
                controlledValue: {
                    c: string;
                };
                openInitially: {
                    c: string;
                };
                excludeSelected: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                normalize: {
                    c: string;
                };
                forceRender: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                fixed: {
                    c: string;
                };
                query: {
                    c: string;
                };
                queryParser: {
                    c: string;
                };
                search: {
                    c: string;
                };
                searchNonce: {
                    c: string;
                };
                searchOptions: {
                    c: string;
                };
                upward: {
                    c: string;
                };
                value: {
                    c: string;
                };
                renderSelected: {
                    c: string;
                };
                noOptionsMsg: {
                    c: string;
                };
                virtualOptionsMinimum: {
                    c: string;
                };
            };
        };
        SelectNested: {
            defaultProps: {
                optionProps: {
                    v: string;
                };
                nestedIcon: {
                    v: string;
                    c: string;
                };
                nestedProps: {
                    v: string;
                };
            };
            propTypes: {
                nestedIcon: {
                    c: string;
                };
                options: {
                    c: string;
                };
                formatKey: {
                    c: string;
                };
                filterValue: {
                    c: string;
                };
            };
        };
        SelectOption: {
            propTypes: {
                option: {};
                onClick: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                focused: {
                    c: string;
                };
                selected: {
                    c: string;
                };
                search: {
                    c: string;
                };
                query: {
                    c: string;
                };
            };
        };
        Switch: {
            defaultProps: {
                className: {
                    v: string;
                };
                checkedValue: {
                    v: string;
                };
                uncheckedValue: {
                    v: string;
                };
            };
            propTypes: {
                controlledValue: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                checkedValue: {
                    c: string;
                };
                uncheckedValue: {
                    c: string;
                };
                label: {
                    c: string;
                };
                checkedLabel: {
                    c: string;
                };
                uncheckedLabel: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                value: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                id: {
                    c: string;
                };
            };
        };
        TextArea: {
            propTypes: {
                compact: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                value: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onFocus: {
                    c: string;
                };
                onBlur: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                label: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                format: {
                    c: string;
                };
                parse: {
                    c: string;
                };
                resize: {
                    c: string;
                };
                noSpellCheck: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                icon: {
                    c: string;
                };
                iconEnd: {
                    c: string;
                };
            };
        };
        Upload: {
            defaultProps: {
                type: {
                    v: string;
                };
                hyphen: {
                    v: string;
                };
                loading: {
                    v: string;
                };
                iconSelect: {
                    v: string;
                };
                iconRemove: {
                    v: string;
                };
                onError: {
                    v: string;
                };
            };
            propTypes: {
                accept: {
                    c: string;
                };
                children: {
                    c: string;
                };
                childBefore: {
                    c: string;
                };
                childAfter: {
                    c: string;
                };
                hyphen: {
                    c: string;
                };
                loading: {
                    c: string;
                };
                maxFiles: {
                    c: string;
                };
                maxSize: {
                    c: string;
                };
                minSize: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                iconSelect: {
                    c: string;
                };
                iconRemove: {
                    c: string;
                };
                square: {
                    c: string;
                };
                value: {
                    c: string;
                };
                defaultValue: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onError: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
            };
        };
        UploadGrid: {
            defaultProps: {
                maxFiles: {
                    v: string;
                };
                gap: {
                    v: string;
                };
                previewAccept: {
                    v: string;
                };
            };
            propTypes: {
                initialValues: {
                    c: string;
                };
                onChange: {
                    c: string;
                };
                onChangeLast: {
                    c: string;
                };
                onRemove: {
                    c: string;
                };
                multiple: {
                    c: string;
                };
                maxFiles: {
                    c: string;
                };
                maxColumns: {
                    c: string;
                };
                gap: {
                    c: string;
                };
                kind: {
                    c: string;
                };
                noPreview: {
                    c: string;
                };
                noPreviewClean: {
                    c: string;
                };
                preview: {
                    c: string;
                };
                previewAccept: {
                    c: string;
                };
                previewClass: {
                    c: string;
                };
                square: {
                    c: string;
                };
                slotLabel: {
                    c: string;
                };
                types: {
                    c: string;
                };
            };
        };
        CodeExample: {
            propTypes: {
                children: {
                    c: string;
                };
                desc: {
                    c: string;
                };
                source: {
                    c: string;
                };
            };
        };
        PropsTable: {
            propTypes: {
                component: {
                    c: string;
                };
                manifest: {
                    c: string;
                };
            };
        };
        TypeHelpTooltip: {
            propTypes: {
                _type: {
                    c: string;
                };
                text: {
                    c: string;
                };
                desc: {
                    c: string;
                };
            };
        };
    } | undefined;
}>;
import * as React from 'react';
