/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
/**
 * Help description popover explaining the control type
 */
export function TypeHelpTooltip({ _type, text, desc }: {
    _type: any;
    text: any;
    desc: any;
}): JSX.Element;
export default TypeHelpTooltipMemo;
export namespace helpTooltipProps {
    let className: string;
    let on: string[];
    let position: string;
    let theme: string;
}
declare const TypeHelpTooltipMemo: React.NamedExoticComponent<ViewProps>;
import * as React from 'react';
