/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface TypeHelpTooltipProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Base type Symbol
   */
  _type?: unknown;
  /**
   * Title text
   */
  text?: string;
  /**
   * Description text
   */
  desc?: string;
}
/**
 * Help description popover explaining the control type
 */
export function TypeHelpTooltip(props: TypeHelpTooltipProps): JSX.Element;

export default TypeHelpTooltipMemo;
export namespace helpTooltipProps {
    let className: string;
    let on: string[];
    let position: string;
    let theme: string;
}
declare const TypeHelpTooltipMemo: React.NamedExoticComponent<TypeHelpTooltipProps>;
import * as React from 'react';
