/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
/**
 * Label - Pure Component.
 * Abstraction layer for React Native, etc.
 */
export function Label({ sound, _ref, ...props }: {
    [x: string]: any;
    sound: any;
    _ref: any;
}, ref: any): JSX.Element;
export const LabelRef: React.ForwardRefExoticComponent<Omit<{
    [x: string]: any;
    sound: any;
    _ref: any;
}, "ref"> & React.RefAttributes<any>>;
export default LabelMemo;
import * as React from 'react';
declare const LabelMemo: React.NamedExoticComponent<ViewProps>;
