/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
/**
 * Selected Option Value as InputView.
 * @example:
 *   import { Select, renderSelected } from '@webframer/ui'
 *       <Select
 *         {...props}
 *         label='Multiple Select (editable)'
 *         multiple search icon={false}
 *         renderSelected={renderSelected}
 *       />
 */
export function SelectValue({ value, index, self, ...props }: {
    [x: string]: any;
    value: any;
    index: any;
    self: any;
}): JSX.Element;
/**
 * Selected Option Renderer for Select Component
 */
export function renderSelected(value: any, index: any, array: any, self: any): JSX.Element;
export default SelectValueMemo;
declare const SelectValueMemo: React.NamedExoticComponent<ViewProps>;
import * as React from 'react';
