/// Generated by Webframe.app | Do not edit this file directly! \\\
export function SelectOption({ option, onClick, onBlur, onFocus, focused, selected, search, query, className, ...props }: {
    [x: string]: any;
    option: any;
    onClick: any;
    onBlur: any;
    onFocus: any;
    focused: any;
    selected: any;
    search: any;
    query: any;
    className: any;
}): JSX.Element;

export function useSelectionOptionProps({ focusIndex, multiple, value, search, query, self, optionProps: optProps, addOption, addOptionMsg, options, noOptionsMsg, forceRender, open, }: {
    focusIndex: any;
    multiple: any;
    value: any;
    search: any;
    query: any;
    self: any;
    optionProps: any;
    addOption: any;
    addOptionMsg: any;
    options: any;
    noOptionsMsg: any;
    forceRender: any;
    open: any;
}): {
    addOption: any;
    noOptions: any;
    optionPropsGetter: (option: any, index: any) => any;
    renderOption: (option: any, index: any, ...args: any[]) => JSX.Element;
    shouldRender: any;
};
export default SelectOptionMemo;
export namespace optionTooltipProps {
    export let className: string;
    export let position: string;
    export let on: string;
    export namespace style {
        let marginInlineStart: string;
        let marginInlineEnd: string;
    }
    let onClick_1: (arg0: Event | undefined) => any;
    export { onClick_1 as onClick };
    export let tabIndex: number;
    export { TIME_DURATION_INSTANT as delay };
}
declare const SelectOptionMemo: React.NamedExoticComponent<SelectOptionProps>;
import * as React from 'react';
