/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
/**
 * Higher Order Component to render Select Options.
 * This component constructs methods and props for Options renderer to consume,
 * where Options renderer is a plugin that can be swapped with VirtualList renderer.
 * It encapsulates away internal logic of Select component by exposing ready-made props.
 */
export function SelectOptions({ fixed, open, upward, optionsProps, forceRender, virtualOptionsMinimum, self, ...restProps }: {
    [x: string]: any;
    fixed: any;
    open: any;
    upward: any;
    optionsProps: any;
    forceRender: any;
    virtualOptionsMinimum: any;
    self: any;
}): JSX.Element;
export function normalizeFocusIndex(focusIndex: any, options: any): any;
export default SelectOptionsMemo;
declare const SelectOptionsMemo: React.NamedExoticComponent<ViewProps>;
import * as React from 'react';
