/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface BadgeProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Badge count
   */
  count: number;
  /**
   * Maximum number of count digits to display
   */
  maxDigits?: number;
}
/**
 * Badge Counter Component.
 * @see https://webframe.app/docs/ui/components/Badge
 */
export function Badge(props: BadgeProps): JSX.Element | null;

export default BadgeMemo;
declare const BadgeMemo: React.NamedExoticComponent<BadgeProps>;
import * as React from 'react';
