/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Breadcrumb item
   */
  items?: Array<{
    icon?: string;
    text: string;
    to?: string;
  } | string | number | boolean | Function>;
  /**
   * Custom breadcrumb items
   */
  children?: string | number | boolean | Function;
}
/**
 * Breadcrumb links
 */
export function Breadcrumb(props: BreadcrumbProps): JSX.Element;

export default BreadcrumbMemo;
declare const BreadcrumbMemo: React.NamedExoticComponent<BreadcrumbProps>;
import * as React from 'react';
