/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface DividerProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * CSS class names as string, separated by space
   */
  className?: string;
  style?: unknown;
}
/**
 * Divider Line - Pure Component.
 * @see https://webframe.app/docs/ui/components/Divider
 */
export function Divider(props: DividerProps): JSX.Element;

export default DividerMemo;
declare const DividerMemo: React.NamedExoticComponent<DividerProps>;
import * as React from 'react';
