/// Generated by Webframe.app | Do not edit this file directly! \\\
import { type } from '../types';
export interface DropdownMenuProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Dropdown Menu content to render when open
   */
  children: string | number | boolean | Function;
  /**
   * Whether to open the Dropdown Menu initially
   */
  open?: boolean;
  /**
   * Three-dots Button props
   */
  btnProps?: {
    /**
     * CSS class names separated by space
     */
    className?: string;
    active?: boolean;
    disabled?: boolean;
    loading?: boolean;
    type?: 'button' | 'submit';
    /**
     * Tooltip props (or content) to display as popup on interaction with this component
     */
    tooltip?: string | number | boolean | Function | {
      children: string | number | boolean | Function;
      on?: 'click' | 'focus' | 'hover' | Array<'click' | 'focus' | 'hover'>;
      position?: 'top' | 'right' | 'bottom' | 'left';
      align?: 'start' | 'end';
      animation?: string;
      delay?: type.Millisecond;
      embedded?: boolean;
      offset?: type.Px;
      openInitially?: boolean;
      onOpen?: Function;
      onClose?: Function;
      onMount?: Function;
      theme?: string;
      /**
       * CSS class names separated by space
       */
      tooltipClass?: string;
    };
    _ref?: Function | {
      current?: {
        getBoundingClientRect: Function;
      };
    };
  };
  /**
   * Three-dots Button Icon props
   */
  iconProps?: {
    font?: boolean;
    /**
     * CSS class names separated by space
     */
    className?: string;
  };
  iconOpen?: string;
  iconClose?: string;
  /**
   * Function({open: boolean, initialOpen: boolean, props, state}) => JSX - custom Menu renderer
   */
  menu?: string | number | boolean | Function;
  /**
   * Dropdown Tooltip props
   */
  tooltipProps?: {
    on?: 'click' | 'focus' | 'hover' | Array<'click' | 'focus' | 'hover'>;
    position?: 'top' | 'right' | 'bottom' | 'left';
    align?: 'start' | 'end';
    animation?: string;
    delay?: type.Millisecond;
    embedded?: boolean;
    offset?: type.Px;
    openInitially?: boolean;
    onOpen?: Function;
    onClose?: Function;
    onMount?: Function;
    theme?: string;
    /**
     * CSS class names separated by space
     */
    tooltipClass?: string;
  };
  /**
   * Handler(self: object) when this component has mounted
   */
  onMount?: Function;
  /**
   * CSS class names separated by space
   */
  className?: string;
  style?: unknown;
}
/**
 * Dropdown Menu that collapses as three-dots Icon initially.
 * Logic:
 *    - Clicking the Icon toggles Dropdown Menu open state
 *    - Uses Tooltip to render the menu.
 *    - To close the Dropdown, call self.tooltip.close() method directly
 */
export function DropdownMenu(props: DropdownMenuProps): JSX.Element;

export default DropdownMenuMemo;
declare const DropdownMenuMemo: React.NamedExoticComponent<DropdownMenuProps>;
import * as React from 'react';
