/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface ErrorContentProps extends React.HTMLAttributes<HTMLElement> {
  items: Array<string | number | {
    id?: any;
    status?: number;
    title?: string;
    detail?: string;
    message?: string;
  }>;
}
/**
 * Error Alert Message Content - Pure Component
 */
export function ErrorContent(props: ErrorContentProps): JSX.Element;

export default ErrorContentMemo;
declare const ErrorContentMemo: React.NamedExoticComponent<ErrorContentProps>;
import * as React from 'react';
