/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface ErrorTableProps extends React.HTMLAttributes<HTMLElement> {
  items: Array<string | number | {
    id?: any;
    status?: number;
    title?: string;
    detail?: string;
    message?: string;
  }>;
}
/**
 * Error Table Listing - Pure Component
 */
export function ErrorTable(props: ErrorTableProps): JSX.Element;

export default ErrorTableMemo;
declare const ErrorTableMemo: React.NamedExoticComponent<ErrorTableProps>;
import * as React from 'react';
