/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface IconProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Icon name, can be empty string to be styled with custom CSS
   */
  name: string;
  /**
   * If `true`, use Font icon, instead of CSS masked image, which is the default
   */
  font?: boolean;
  /**
   * CSS class names separated by space
   */
  className?: string;
  style?: unknown;
}
/**
 * Icon - Pure Component.
 * @see https://webframe.app/docs/ui/components/Icon
 */
export function Icon(props: IconProps): JSX.Element;

export default IconMemo;
declare const IconMemo: React.NamedExoticComponent<IconProps>;
import * as React from 'react';
