/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface ImageSwatchProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Full Path, URL, Base64 or Preview String object of Image file
   */
  src: string;
  small?: boolean;
  large?: boolean;
  /**
   * CSS class names as string, separated by space
   */
  className?: string;
  style?: unknown;
}
/**
 * Image Swatch - Dumb Component
 */
export function ImageSwatch(props: ImageSwatchProps): JSX.Element;

export default ImageSwatchMemo;
declare const ImageSwatchMemo: React.NamedExoticComponent<ImageSwatchProps>;
import * as React from 'react';
