/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface JsonViewProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * JSON data to display (as `Collection` of values)
   */
  data: object | Array<unknown>;
  /**
   * Whether to render in dark mode with inverted theme color
   */
  dark?: boolean;
  /**
   * Whether to expand all nodes
   */
  open?: boolean;
  /**
   * Color scheme
   */
  theme?: object;
}
/**
 * JSON Data Renderer for Nested Collections
 */
export function JsonView(props: JsonViewProps): JSX.Element;

export default JsonViewMemo;
import defaultTheme from './JsonView.themes.js';
declare const JsonViewMemo: React.NamedExoticComponent<JsonViewProps>;
import * as React from 'react';
