/// Generated by Webframe.app | Do not edit this file directly! \\\
export namespace nicinabox {
    let scheme: string;
    let author: string;
    let base00: string;
    let base01: string;
    let base02: string;
    let base03: string;
    let base04: string;
    let base05: string;
    let base06: string;
    let base07: string;
    let base08: string;
    let base09: string;
    let base0A: string;
    let base0B: string;
    let base0C: string;
    let base0D: string;
    let base0E: string;
    let base0F: string;
}
export default nicinabox;
