/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface MarkdownProps extends React.HTMLAttributes<HTMLElement> {
  children: string;
  /**
   * key -> value pairs where `key` is element tag name, and `value` is the render function
   * 
   * @see https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight
   */
  components?: unknown;
  remarkPlugins?: Array<any>;
  rehypePlugins?: Array<any>;
  remarkRehypeOptions?: any;
}
/**
 * Markdown View - Pure Component.
 * Features:
 *    - Ctrl + A will select only markdown content, not the entire viewport
 */
export function Markdown(props: MarkdownProps): JSX.Element;

export default MarkdownMemo;
declare const MarkdownMemo: React.NamedExoticComponent<MarkdownProps>;
import * as React from 'react';
