/// Generated by Webframe.app | Do not edit this file directly! \\\
export const atomDark: {
    'code[class*="language-"]': {
        color: string;
        textShadow: string;
        fontFamily: string;
        direction: string;
        textAlign: string;
        whiteSpace: string;
        wordSpacing: string;
        wordBreak: string;
        lineHeight: string;
        MozTabSize: string;
        OTabSize: string;
        tabSize: string;
        WebkitHyphens: string;
        MozHyphens: string;
        msHyphens: string;
        hyphens: string;
    };
    'pre[class*="language-"]': {
        color: string;
        textShadow: string;
        fontFamily: string;
        direction: string;
        textAlign: string;
        whiteSpace: string;
        wordSpacing: string;
        wordBreak: string;
        lineHeight: string;
        MozTabSize: string;
        OTabSize: string;
        tabSize: string;
        WebkitHyphens: string;
        MozHyphens: string;
        msHyphens: string;
        hyphens: string;
        padding: string;
        margin: string;
        overflow: string;
        borderRadius: string;
        background: string;
    };
    ':not(pre) > code[class*="language-"]': {
        background: string;
        padding: string;
        borderRadius: string;
    };
    comment: {
        color: string;
    };
    prolog: {
        color: string;
    };
    doctype: {
        color: string;
    };
    cdata: {
        color: string;
    };
    punctuation: {
        color: string;
    };
    '.namespace': {
        Opacity: string;
    };
    property: {
        color: string;
    };
    keyword: {
        color: string;
    };
    tag: {
        color: string;
    };
    'class-name': {
        color: string;
        textDecoration: string;
    };
    boolean: {
        color: string;
    };
    constant: {
        color: string;
    };
    symbol: {
        color: string;
    };
    deleted: {
        color: string;
    };
    number: {
        color: string;
    };
    selector: {
        color: string;
    };
    'attr-name': {
        color: string;
    };
    string: {
        color: string;
    };
    char: {
        color: string;
    };
    builtin: {
        color: string;
    };
    inserted: {
        color: string;
    };
    variable: {
        color: string;
    };
    operator: {
        color: string;
    };
    entity: {
        color: string;
        cursor: string;
    };
    url: {
        color: string;
    };
    '.language-css .token.string': {
        color: string;
    };
    '.style .token.string': {
        color: string;
    };
    atrule: {
        color: string;
    };
    'attr-value': {
        color: string;
    };
    function: {
        color: string;
    };
    regex: {
        color: string;
    };
    important: {
        color: string;
        fontWeight: string;
    };
    bold: {
        fontWeight: string;
    };
    italic: {
        fontStyle: string;
    };
};
