/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface ModalProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Whether to allow closing of the Modal
   */
  canClose?: boolean;
  /**
   * Whether to open the Modal (i.e. set it to `active`)
   */
  open?: boolean;
  /**
   * Callback (e: Event) => void  for Modal close event
   */
  onClose?: Function;
}
/**
 * Modal to overlay content with a closable popup screen
 */
export function Modal(props: ModalProps): JSX.Element;

export default ModalMemo;
declare const ModalMemo: React.NamedExoticComponent<ModalProps>;
import * as React from 'react';
