/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
export const Row: (props: ViewProps) => JSX.Element;
export default RowMemo;
declare const RowMemo: React.NamedExoticComponent<ViewProps>;
import * as React from 'react';
