/// Generated by Webframe.app | Do not edit this file directly! \\\
import { ViewProps } from '../components/View';
export const Scroll: (props: ViewProps) => JSX.Element;
export default ScrollMemo;
declare const ScrollMemo: React.NamedExoticComponent<ViewProps>;
import * as React from 'react';
