/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface ShadowDOMProps extends React.HTMLAttributes<HTMLElement> {
  mode?: 'open' | 'closed';
  delegatesFocus?: boolean;
  /**
   * From [CSSStyleSheet()](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/adoptedStyleSheets)
   */
  styleSheets?: Array<any>;
  ssr?: boolean;
  children?: string | number | boolean | Function;
}
/**
 * Based on [react-shadow](https://github.com/Wildhoney/ReactShadow) package.
 */
export function ShadowDOM(props: ShadowDOMProps): JSX.Element;

/**
 * Get element.shadowRoot object
 * @returns {ShadowRoot|null} shadowRoot
 */
export function useShadowRoot(): ShadowRoot | null;
export default ShadowDOMMemo;
export const ShadowRootContext: React.Context<null>;
declare const ShadowDOMMemo: React.NamedExoticComponent<ShadowDOMProps>;
import * as React from 'react';
