/// Generated by Webframe.app | Do not edit this file directly! \\\
export interface SpinnerProps extends React.HTMLAttributes<HTMLElement> {
  size?: 'smallest' | 'smaller' | 'small' | 'base' | 'large' | 'larger' | 'largest';
  color?: 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error' | 'dark' | 'grey' | 'light' | 'neutral';
  className?: unknown;
}
/**
 * Spinner - Pure Component
 *
 * @param {string} size - spinner size
 * @param {string} color - spinner color
 * @param {string} className - optional, will be prepended with spinner classes
 * @param {boolean} [loading] - whether to animate the spinner
 * @param {*} props - other attributes to pass to spinner
 * @returns {object} - React Component
 */
export function Spinner(props: SpinnerProps): object;

export default SpinnerMemo;
declare const SpinnerMemo: React.NamedExoticComponent<SpinnerProps>;
import * as React from 'react';
